configfile: "snakemake_lib/snakefile_config.yaml"

include: "snakemake_lib/fastp.sm"
include: "snakemake_lib/combined.sm"
include: "snakemake_lib/count_table.sm"
include: "snakemake_lib/deseq2.sm"
include: "snakemake_lib/bamcoverage.sm"
include: "snakemake_lib/multiqc.sm"
include: "snakemake_lib/preprocessing.sm"
include: "snakemake_lib/variant_calling.sm"

rule all:
    input:
        rules.combined__all.input,
        rules.count_table__all.input,
        rules.deseq2__all.input,
        rules.bamcoverage__all.input,
        rules.multiqc__all.input,
        rules.preprocessing__all.input,
        rules.variant_calling__all.input,
